### ISSUE TITLE
Chapter 2 jquery https://github.com/Abdul-Azeez/jqueryfundamentals/blob/master/exercises/js/sandbox.js

### ISSUE THREAD

**Issue by Abdul-Azeez** [Abdul-Azeez/jqueryfundamentals#1]
https://github.com/Abdul-Azeez/jqueryfundamentals/blob/master/exercises/js/sandbox.js

**Comment by abhishekjain16** [comment]
1. $collectimageattr =$('img[alt]');
   console.log($collectimageattr);

We need to log alt attribute not elements.
1. $selectinput = $('form#search input[type ="text"]');
   console.log($selectinput);
   console.log($selectinput.parent());
   $selectinput.parent().addClass("input");

What if this is not immediate parent

**Comment by Abdul-Azeez** [comment]
Done
